FROM python:3.9-slim

RUN mkdir -p /app/db && \
    chown -R 1000:1000 /app

WORKDIR /app

COPY scripts/requirements.txt requirements.txt
RUN pip install -r requirements.txt

COPY scripts/ .

# Install Flask
RUN pip install Flask

# Expose the port Flask will run on
EXPOSE 5000

# Run hello_world.py before starting the Flask app
CMD ["sh", "-c", "python hello_world.py && python app.py"]
