version: '3.8'

services:
  script-executor:
    build:
      context: .
      dockerfile: Dockerfile.script-executor
    depends_on:
      - database-service
    volumes:
      - ./scripts:/app
      - ./data:/app/data
      - ./database:/app/db
    ports:
      - "5000:5000"
    user: "1000:1000"

  database-service:
    build:
      context: .
      dockerfile: Dockerfile.database-service
    volumes:
      - ./database:/app/db
    user: "1000:1000"