FROM python:3.9-slim

RUN mkdir -p /app/db && \
    chown -R 1000:1000 /app

WORKDIR /app

COPY scripts/requirements.txt requirements.txt
RUN pip install -r requirements.txt

COPY scripts/ .

CMD ["python", "hello_world.py"]